version: 2
jobs:
  pip:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: python3 -m venv venv
      - run: |
          . venv/bin/activate
          pip install -r requirements.txt
      - run: |
          . venv/bin/activate
          jupyter labextension install jupyterlab-mapd@0.3.0
      - run: |
          . venv/bin/activate
          ./test.bash
  conda:
    docker:
      - image: continuumio/miniconda
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: conda env create -f environment.yml
      - run: |
          conda activate mapd
          jupyter labextension install jupyterlab-mapd@0.3.0
      - run: |
          conda activate mapd
          ./test.bash
workflows:
  version: 2
  test:
    jobs:
      - pip
      - conda
