version: 2
jobs:
  pip:
    docker:
      - image: circleci/python:3.6-stretch-node
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: python3 -m venv venv
      - run: |
          . venv/bin/activate
          pip install -r requirements.txt
      - run: |
          . venv/bin/activate
          jupyter labextension install jupyterlab-mapd@0.3.0
      - run: |
          . venv/bin/activate
          ./test.bash
  conda:
    docker:
      - image: continuumio/miniconda
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: conda env create -f environment.yml
      - run: echo 'export PATH=/opt/conda/envs/mapd/bin:$PATH' >> $BASH_ENV
      - run: jupyter labextension install jupyterlab-mapd@0.3.0
      - run: ./test.bash
  version: 2
  test:
    jobs:
      - pip
      - conda
