version: 2
jobs:
  pip:
    docker:
      - image: circleci/python:3.6-stretch-node
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: python3 -m venv venv
      - run: |
          . venv/bin/activate
          pip install -r requirements.txt
      - run: |
          . venv/bin/activate
          jupyter labextension install jupyterlab-mapd
      - run: |
          . venv/bin/activate
          ./test.bash
  conda:
    docker:
      - image: continuumio/miniconda
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - run: conda env create -f environment.yml
      - run: echo 'export PATH=/opt/conda/envs/mapd/bin:$PATH' >> $BASH_ENV
      - run: jupyter labextension install jupyterlab-mapd
      - run: ./test.bash
  docker:
    docker:
      - image: circleci/buildpack-deps
    working_directory: ~/repo/notebooks
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker
      - run: docker-compose build jupyter
      - run: docker-compose run jupyter ./test.bash
workflows:
  version: 2
  test:
    jobs:
      - pip
      - conda
      - docker
    triggers:
      - schedule:
          cron: "0 0 * * *"
