name: mapd
channels:
  - conda-forge
dependencies:
  - python=3.6
  - jupyterlab=0.34.*
  - pymapd
  - altair
  - nodejs
  - pyyaml
  - regex
  - ipywidgets
  - pip:
    - git+https://github.com/Quansight/jupyter-mapd-renderer.git#egg=jupyter-mapd-renderer[altair]
    - git+https://github.com/Quansight/ibis.git@add_rowid_op#egg=ibis-framework
